### ISSUE TITLE
cartopy 0.18 required?

### ISSUE THREAD

**Issue by mathause** [conda-forge/cartopy_offlinedata-feedstock#10]
Is there a reason cartopy >= 0.18 is required? This is not enforced in the [setup.py](https://github.com/willirath/cartopy_offlinedata/blob/master/setup.py). As far as I can see the `cartopy_userconfig` hook is in cartopy for a long time.

https://github.com/conda-forge/cartopy_offlinedata-feedstock/blob/2d633324e57f8372501c848395705ebb1385a2ac/recipe/meta.yaml#L24

I have conda environments where I would like to avoid updating packages so with the recent change in URL this is very helpful.

**Comment by willirath** [comment]
Not sure. I think @xylar added this line when updating to the latest version of the package. But I'm not sure this was really needed.

**Comment by xylar** [comment]
It has been a year and a half since I added that constraint and I didn't say why.  But my vague memory is that things changed in how the data gets downloaded.  Maybe the constraint is only necessary in host and not in run.

@mathause, is there a reason you want to use an older version?  I'm not particularly inclined to do a new build with a looser constraint that I'm not 100% sure will work unless it's really needed.

**Comment by mathause** [comment]
Thanks everyone for the fast reply.

> is there a reason you want to use an older version?

I manage some institute-wide environments which I want to keep frozen so I don't break anyone's code. Installing cartopy_offlinedata would be a nice and easy workaround for the changed naturalearth data url change.

 > I'm not particularly inclined to do a new build with a looser constraint that I'm not 100% sure will work unless it's really needed.

Yes makes sense! So let's leave it as is - there are other ways to fix the issue.

**Comment by willirath** [comment]
> is there a reason you want to use an older version? I'm not particularly inclined to do a new build with a looser constraint that I'm not 100% sure will work unless it's really needed.

OTOH (and off topic): Would be a good opportunity to learn how to build and test recipes and resulting conda packages locally. I think https://conda-forge.org/docs/maintainer/updating_pkgs.html#testing-changes-locally gives us everything we need for this?

**Comment by xylar** [comment]
Right, that would be my suggestion.  You could clone the recipe, take out the `cartopy >= 0.18` constraint, bump the build number if you like, build the package locally, and install it using `--use-local`.  I'd be happy to help with the local build if you run into trouble.
