### ISSUE TITLE
Package is finally (largely) obsolete 🎉

### ISSUE THREAD

**Issue by willirath** [conda-forge/cartopy_offlinedata-feedstock#11]
### Comment:

Since cartopy v0.20, there's an env variable `${CARTOPY_DATA_DIR}` which cartopy directly uses for setting the path to pre-existing data. In addition, there now is a `stalled when cartopy is installed which provides feature download.

So we could boil down this package to:

1. install cartopy at build time
2. run `cartopy_feature_download.py --output ${PREFIX}/... gshhs physical cultural cultural-extra`
3. Make sure `${CARTOPY_DATA_DIR}` is set when the env activates.

Only thing missing would be the Antarctic ice shelf polygons which @xylar added.

**Comment by xylar** [comment]
Great, I'll see if I can just use `cartopy` directly.  If so, the version of `cartopy_offlinedata` can match the version of `cartopy` from now on.

**Comment by willirath** [comment]
And we should find a way of ensuring the bot also updates here whenever a new release of Cartopy is out.
