### ISSUE TITLE
Should we use the conda-forge version of Cartopy rather than that on PyPi?

### ISSUE THREAD

**Issue by willirath** [conda-forge/cartopy_offlinedata-feedstock#15]
### Comment:

Currently, this package follows the PyPi version: https://github.com/conda-forge/cartopy_offlinedata-feedstock/blob/08a2a178fbedd52ab202e7dc6db53d1bcc51be43/recipe/meta.yaml#L10

As the Conda-Forge package may lag behind this at least a few hours, we'd probably want to depend on the Conda-Forge package version? Not sure how we do this.

Pinging @ocefpaf

**Comment by xylar** [comment]
@willirath, it is normal that we get the source code for PyPI on conda-forge. We could get it from GitHub instead but not from conda-forge itself.

**Comment by xylar** [comment]
Note that the cartopy recipe itself gets source from PyPI:
https://github.com/conda-forge/cartopy-feedstock/blob/main/recipe/meta.yaml#L8

**Comment by xylar** [comment]
> As the Conda-Forge package may lag behind this at least a few hours, we'd probably want to depend on the Conda-Forge package version? Not sure how we do this.

I'm a maintainer on both this and the cartopy feedstock, so I can just wait until a the cartopy package is ready to merge this.  I don't think there's a good alternative unless we make this part of the main carotpy recipe or have a bot migrator for cartopy (neither if which seems appealing to me).

**Comment by xylar** [comment]
I'm going to close this because I don't think there's anything to do.
